name: lint

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    name: check ${{ matrix.python-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: uv Install Dependencies
        run: |
          uv sync --group dev

      - name: pyright
        id: pyright
        continue-on-error: true
        run: |
          uv run pyright .

      - name: mypy
        id: mypy
        continue-on-error: true
        run: |
          uv run mypy .

      - name: ruff-check
        id: ruff-check
        continue-on-error: true
        run: |
          uv run ruff check --no-fix --output-format=github .

      - name: ruff-format
        id: ruff-format
        continue-on-error: true
        run: |
          uv run ruff format --check --diff .

      - name: Check failure
        env:
          text: "\
            ${{ steps.ruff-format.outcome == 'failure'        && 'ruff format,'     || '' }}\
            ${{ steps.ruff-check.outcome == 'failure'         && 'ruff check,'      || '' }}\
            ${{ steps.pyright.outcome == 'failure'            && 'pyright,'         || '' }}\
            ${{ steps.mypy.outcome == 'failure'               && 'mypy,'            || '' }}\
            "
        run: |
          if [ -n "${text}" ]; then
            echo "failed: ${text}"
            exit 1
          else
            echo "All success"
          fi
